### ISSUE TITLE
redo all constants to PCA963X_xxxx to sync PCA9634/35

### ISSUE THREAD

**Issue by RobTillaart** [RobTillaart/PCA9634#28]

**Comment by Luxovious** [comment]
Hi @RobTillaart,
I have been absent for a while because I have been very busy. In case you need me to test any functions for you on the PCA9634, please let me know, I'm happy to help.

I am really happy to see that you continue to develop those libraries and preparing a merge.

Best regards Johannes

**Comment by RobTillaart** [comment]
Babysteps

**Comment by RobTillaart** [comment]
all PCA963X added in 0.2.8 
(remove of old defines when 0.3.0 arrives someday in the future)
